services:
  - type: web
    name: american-latin-class-api
    runtime: image
    repo: https://github.com/EvelynVillarreal/AWD-30716-Code-Coffee
    plan: free
    region: oregon
    dockerfilePath: ./06Code/Dockerfile
    dockerContext: ./06Code
    envVars:
      - key: APP_KEY
        sync: false
      - key: DB_HOST
        sync: false
      - key: DB_PORT
        sync: false
      - key: DB_DATABASE
        sync: false
      - key: DB_USERNAME
        sync: false
      - key: DB_PASSWORD
        sync: false
      - key: DB_SSLMODE
        value: require
      - key: FRONTEND_ORIGINS
        value: https://american-latin-class-frontend.onrender.com,https://creative-pothos-6c7a4c.netlify.app
      - key: APP_ENV
        value: production
      - key: APP_DEBUG
        value: "false"
      - key: APP_TIMEZONE
        value: America/Bogota
    healthCheckPath: /api/health
    autoDeploy: true
